// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IMMessage.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

GPB_ENUM_FWD_DECLARE(MessageType);

NS_ASSUME_NONNULL_BEGIN

#pragma mark - ImmessageRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface ImmessageRoot : GPBRootObject
@end

#pragma mark - IMMessageReq

typedef GPB_ENUM(IMMessageReq_FieldNumber) {
  IMMessageReq_FieldNumber_Form = 1,
  IMMessageReq_FieldNumber_To = 2,
  IMMessageReq_FieldNumber_Type = 3,
  IMMessageReq_FieldNumber_Create = 4,
  IMMessageReq_FieldNumber_Body = 5,
};

/**
 * 消息发送
 **/
GPB_FINAL @interface IMMessageReq : GPBMessage

/** 消息发送方 */
@property(nonatomic, readwrite) uint32_t form;

/** 消息接收方 */
@property(nonatomic, readwrite) uint32_t to;

/** 消息类型 */
@property(nonatomic, readwrite) enum MessageType type;

/** 消息的发送时间 */
@property(nonatomic, readwrite) uint32_t create;

/** 消息内容 */
@property(nonatomic, readwrite, copy, null_resettable) NSData *body;

@end

/**
 * Fetches the raw value of a @c IMMessageReq's @c type property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t IMMessageReq_Type_RawValue(IMMessageReq *message);
/**
 * Sets the raw value of an @c IMMessageReq's @c type property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetIMMessageReq_Type_RawValue(IMMessageReq *message, int32_t value);

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
